### ISSUE TITLE
what all scopes are needed for this to work?

### ISSUE THREAD

**Issue by ion9** [SpeedProg/eve-inc-waitlist#7]
i have, 
    characterLocationRead
    characterNavigationWrite
    characterSkillsRead
    characterClonesRead
but i'm thinking i'll need to add some more.

**Comment by ion9** [comment]
i found esi-ui.open_window.v1 esi-fleets.read_fleet.v1 esi-fleets.write_fleet.v1 called out in fc_sso.py

**Comment by itshouldntdothis** [comment]
- esi-mail.send_mail.v1
- esi-fleets.read_fleet.v1
- esi-fleets.write_fleet.v1
- esi-ui.open_window.v1
Should cover all of the scopes currently used.

**Comment by SpeedProg** [comment]
https://github.com/SpeedProg/eve-inc-waitlist/blob/master/setup_basic.py
contains the list
but yeah this should be added to documentation

**Comment by SpeedProg** [comment]
done with 920d6c1b35cbec9cd99bc51db0f053d8045da3a0
