### ISSUE TITLE
Fix WL title

### ISSUE THREAD

**Issue by Gashans** [SpeedProg/eve-inc-waitlist#8]
IT please, trying to change the WL title from HQ to Vanguard gives Internal Server error... everything else seems to be working...

Did you try a work around like VG fleet?

Was manually writing "Vanguard", exact same as the 3rd fleet down

Hmm odd, one would think if it works as a drop down it should work.
Just in case anyone is confused, council has a text box for fleet status not a drop down.

yeah, I'd always wondered how you guys put weird stuff in the Running/forming/down section untill I got officer :leichtes_lächeln:

;)
You should be able to write anything in there

**Comment by SpeedProg** [comment]
should be fixed with 2bffcb597aafa35c6e4620632bbcd0b815a1ef25
